-- Execute antes de reimportar CSV com mais registros

DELETE FROM SENSORS;
DELETE FROM PRODUCTION;

COMMIT;

SELECT 'PRODUCTION' AS tabela, COUNT(*) AS total FROM PRODUCTION
UNION ALL
SELECT 'SENSORS', COUNT(*) FROM SENSORS;
