"""
Sistema de Gestão de Produção e Perdas na Colheita de Cana-de-Açúcar.

FIAP - Fase 2 - Capítulo 6
Domínio: agronegócio sucroalcooleiro.

Problema tratado: a colheita mecanizada de cana chega a 15% de perda
(contra ~5% da manual), gerando prejuízo de cerca de R$ 20 mi/ano só em SP.
Esta solução permite registrar a produção por fazenda, calcular o prejuízo
em reais, comparar com benchmarks do setor e exportar relatórios.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Callable

import oracledb

# Carrega variaveis do arquivo .env, se existir. O .env fica fora do git
# (ignorado pelo .gitignore) e permite trocar entre o Oracle local via
# Docker e o Oracle institucional da FIAP sem alterar codigo.
try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    # python-dotenv nao instalado — seguimos apenas com variaveis ja
    # exportadas no shell. A aplicacao continua funcionando normalmente.
    pass


# =============================================================
# Constantes do domínio (benchmarks do setor sucroalcooleiro)
# =============================================================
PRICE_PER_TON_BRL = 120.00
MANUAL_LOSS_BENCHMARK_PCT = 5.0
MECHANICAL_LOSS_BENCHMARK_PCT = 15.0

# Tupla — opções fixas de tipo de colheita.
HARVEST_TYPES: tuple[str, ...] = ("manual", "mecanizada")


# =============================================================
# Configuração da conexão Oracle (via variáveis de ambiente)
# =============================================================
ORACLE_USER = os.getenv("ORACLE_USER", "")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD", "")
ORACLE_DSN = os.getenv("ORACLE_DSN", "oracle.fiap.com.br:1521/ORCL")


# =============================================================
# Camada de banco de dados (Oracle)
# =============================================================
def connect() -> oracledb.Connection:
    """Abre conexão com o Oracle no modo thin (sem Oracle Client)."""
    return oracledb.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=ORACLE_DSN,
    )


def create_table() -> None:
    """Cria a tabela `producao` se ainda não existir."""
    ddl = """
        CREATE TABLE producao (
            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            farm          VARCHAR2(100) NOT NULL,
            tons          NUMBER(12, 2) NOT NULL,
            loss_pct      NUMBER(5, 2)  NOT NULL,
            harvest_type  VARCHAR2(20)  NOT NULL,
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
    with connect() as conn, conn.cursor() as cursor:
        try:
            cursor.execute(ddl)
            conn.commit()
        except oracledb.DatabaseError as exc:
            (error,) = exc.args
            # ORA-00955: nome já em uso — a tabela já existe, ok ignorar.
            if error.code != 955:
                raise


def insert_record(
    farm: str, tons: float, loss_pct: float, harvest_type: str
) -> None:
    """Insere um novo registro de produção no Oracle."""
    sql = """
        INSERT INTO producao (farm, tons, loss_pct, harvest_type)
        VALUES (:farm, :tons, :loss_pct, :harvest_type)
    """
    with connect() as conn, conn.cursor() as cursor:
        cursor.execute(
            sql,
            farm=farm,
            tons=tons,
            loss_pct=loss_pct,
            harvest_type=harvest_type,
        )
        conn.commit()


def fetch_all_records() -> list[tuple]:
    """Retorna todos os registros como uma lista de tuplas (vindas do cursor)."""
    sql = """
        SELECT id, farm, tons, loss_pct, harvest_type, created_at
        FROM producao
        ORDER BY id
    """
    with connect() as conn, conn.cursor() as cursor:
        cursor.execute(sql)
        return cursor.fetchall()


def delete_record(record_id: int) -> int:
    """Apaga um registro pelo id. Retorna o número de linhas afetadas."""
    sql = "DELETE FROM producao WHERE id = :record_id"
    with connect() as conn, conn.cursor() as cursor:
        cursor.execute(sql, record_id=record_id)
        affected = cursor.rowcount
        conn.commit()
        return affected


# =============================================================
# Tabela de memória (cache de registros lidos do banco)
# =============================================================
# Lista de dicionários, populada a partir das tuplas devolvidas pelo cursor.
# Funciona como índice em RAM para análises sem ir ao banco a cada operação.
_memory_table: list[dict] = []


def refresh_memory_table() -> None:
    """Recarrega a tabela de memória a partir do Oracle."""
    global _memory_table
    rows = fetch_all_records()
    _memory_table = [
        {
            "id": row[0],
            "farm": row[1],
            "tons": float(row[2]),
            "loss_pct": float(row[3]),
            "harvest_type": row[4],
            "created_at": row[5],
        }
        for row in rows
    ]


# =============================================================
# Regras de negócio (cálculos sobre as perdas)
# =============================================================
def calculate_loss(tons: float, loss_pct: float) -> dict:
    """Calcula a perda em toneladas e em reais."""
    lost_tons = tons * (loss_pct / 100)
    lost_brl = lost_tons * PRICE_PER_TON_BRL
    return {"lost_tons": lost_tons, "lost_brl": lost_brl}


def benchmark_for(harvest_type: str) -> float:
    """Retorna o benchmark de perda do setor para o tipo de colheita."""
    if harvest_type == "manual":
        return MANUAL_LOSS_BENCHMARK_PCT
    return MECHANICAL_LOSS_BENCHMARK_PCT


def benchmark_message(loss_pct: float, harvest_type: str) -> str:
    """Compara a perda informada com o benchmark do tipo de colheita."""
    benchmark = benchmark_for(harvest_type)
    if loss_pct > benchmark:
        diff = loss_pct - benchmark
        return (
            f"ALERTA: perda {diff:.1f} p.p. acima do benchmark "
            f"({benchmark}%) para colheita {harvest_type}."
        )
    return (
        f"OK: perda dentro do benchmark do setor "
        f"({benchmark}% para colheita {harvest_type})."
    )


# =============================================================
# Validação de entrada do usuário
# =============================================================
def read_text(prompt: str, *, min_length: int = 1, max_length: int = 100) -> str:
    """Lê uma string não vazia dentro de um intervalo de tamanho."""
    while True:
        value = input(prompt).strip()
        if min_length <= len(value) <= max_length:
            return value
        print(f"  Erro: digite entre {min_length} e {max_length} caracteres.")


def read_float(prompt: str, *, minimum: float, maximum: float) -> float:
    """Lê um float dentro de um intervalo, aceitando vírgula decimal."""
    while True:
        raw = input(prompt).strip().replace(",", ".")
        try:
            value = float(raw)
        except ValueError:
            print("  Erro: digite apenas números (ex.: 1234.56).")
            continue
        if minimum <= value <= maximum:
            return value
        print(f"  Erro: o valor deve estar entre {minimum} e {maximum}.")


def read_int(prompt: str, *, minimum: int, maximum: int) -> int:
    """Lê um inteiro dentro de um intervalo."""
    while True:
        raw = input(prompt).strip()
        try:
            value = int(raw)
        except ValueError:
            print("  Erro: digite um número inteiro.")
            continue
        if minimum <= value <= maximum:
            return value
        print(f"  Erro: o valor deve estar entre {minimum} e {maximum}.")


def read_choice(prompt: str, options: tuple[str, ...]) -> str:
    """Lê uma opção entre as válidas."""
    options_str = "/".join(options)
    while True:
        value = input(f"{prompt} ({options_str}): ").strip().lower()
        if value in options:
            return value
        print(f"  Erro: escolha uma das opções: {options_str}.")


# =============================================================
# Manipulação de arquivos (JSON e texto)
# =============================================================
JSON_PATH = "producao.json"
TXT_PATH = "relatorio.txt"


def export_json(records: list[dict]) -> str:
    """Salva os registros em arquivo JSON estruturado."""
    serializable = [
        {
            **r,
            "created_at": (
                r["created_at"].isoformat()
                if isinstance(r["created_at"], datetime)
                else r["created_at"]
            ),
        }
        for r in records
    ]
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(serializable, f, indent=4, ensure_ascii=False)
    return JSON_PATH


def export_txt(records: list[dict]) -> str:
    """Salva um relatório formatado em arquivo de texto."""
    lines = [
        "RELATORIO DE PRODUCAO E PERDAS - CANA-DE-ACUCAR",
        "=" * 90,
        f"{'ID':>3} | {'Fazenda':<25} | {'Tons':>10} | "
        f"{'Perda%':>7} | {'Perda(t)':>10} | {'Perda(R$)':>14} | Tipo",
        "-" * 90,
    ]
    for r in records:
        loss = calculate_loss(r["tons"], r["loss_pct"])
        lines.append(
            f"{r['id']:>3} | {r['farm']:<25} | {r['tons']:>10.2f} | "
            f"{r['loss_pct']:>6.2f}% | {loss['lost_tons']:>10.2f} | "
            f"R$ {loss['lost_brl']:>11,.2f} | {r['harvest_type']}"
        )
    lines.append("=" * 90)
    with open(TXT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return TXT_PATH


# =============================================================
# Apresentação no terminal
# =============================================================
def print_records_table(records: list[dict]) -> None:
    """Imprime a tabela de registros formatada com totais agregados."""
    if not records:
        print("\n  Nenhum registro cadastrado.\n")
        return

    print()
    print(
        f"  {'ID':>3} | {'Fazenda':<25} | {'Tons':>10} | {'Perda%':>7} | "
        f"{'Perda(t)':>10} | {'Perda(R$)':>14} | Tipo"
    )
    print("  " + "-" * 98)

    total_tons = 0.0
    total_loss_tons = 0.0
    total_loss_brl = 0.0

    for r in records:
        loss = calculate_loss(r["tons"], r["loss_pct"])
        total_tons += r["tons"]
        total_loss_tons += loss["lost_tons"]
        total_loss_brl += loss["lost_brl"]
        print(
            f"  {r['id']:>3} | {r['farm']:<25} | {r['tons']:>10.2f} | "
            f"{r['loss_pct']:>6.2f}% | {loss['lost_tons']:>10.2f} | "
            f"R$ {loss['lost_brl']:>11,.2f} | {r['harvest_type']}"
        )

    print("  " + "-" * 98)
    print(
        f"  TOTAIS: {total_tons:>10.2f} t produzidas  |  "
        f"{total_loss_tons:>10.2f} t perdidas  |  "
        f"R$ {total_loss_brl:>11,.2f} de prejuizo"
    )
    print()


# =============================================================
# Acoes do menu
# =============================================================
def action_register() -> None:
    print("\n--- Cadastrar producao ---")
    farm = read_text("  Nome da fazenda: ")
    tons = read_float("  Producao (toneladas): ", minimum=0.01, maximum=1_000_000)
    loss_pct = read_float("  Perda (%): ", minimum=0.0, maximum=100.0)
    harvest_type = read_choice("  Tipo de colheita", HARVEST_TYPES)

    insert_record(farm, tons, loss_pct, harvest_type)
    refresh_memory_table()

    loss = calculate_loss(tons, loss_pct)
    print(
        f"\n  Registro salvo. Perda calculada: {loss['lost_tons']:.2f} t "
        f"(R$ {loss['lost_brl']:,.2f})"
    )
    print(f"  {benchmark_message(loss_pct, harvest_type)}\n")


def action_list() -> None:
    refresh_memory_table()
    print_records_table(_memory_table)


def action_delete() -> None:
    refresh_memory_table()
    if not _memory_table:
        print("\n  Nenhum registro para apagar.\n")
        return
    print_records_table(_memory_table)
    record_id = read_int("  ID a apagar: ", minimum=1, maximum=10**9)
    affected = delete_record(record_id)
    if affected:
        refresh_memory_table()
        print(f"  Registro {record_id} apagado.\n")
    else:
        print(f"  Nenhum registro encontrado com id {record_id}.\n")


def action_export_json() -> None:
    refresh_memory_table()
    if not _memory_table:
        print("\n  Nada para exportar.\n")
        return
    path = export_json(_memory_table)
    print(f"\n  Dados exportados para {path}\n")


def action_export_txt() -> None:
    refresh_memory_table()
    if not _memory_table:
        print("\n  Nada para exportar.\n")
        return
    path = export_txt(_memory_table)
    print(f"\n  Relatorio exportado para {path}\n")


def action_summary() -> None:
    refresh_memory_table()
    if not _memory_table:
        print("\n  Sem dados para analise.\n")
        return

    by_type: dict[str, list[dict]] = {ht: [] for ht in HARVEST_TYPES}
    for r in _memory_table:
        by_type[r["harvest_type"]].append(r)

    print("\n--- Resumo por tipo de colheita ---")
    for harvest_type, records in by_type.items():
        if not records:
            continue
        avg_loss = sum(r["loss_pct"] for r in records) / len(records)
        total_brl = sum(
            calculate_loss(r["tons"], r["loss_pct"])["lost_brl"]
            for r in records
        )
        benchmark = benchmark_for(harvest_type)
        status = "ACIMA" if avg_loss > benchmark else "DENTRO"
        print(f"\n  Colheita {harvest_type}:")
        print(f"    Registros:      {len(records)}")
        print(
            f"    Perda media:    {avg_loss:.2f}%  "
            f"(benchmark do setor: {benchmark}% -> {status})"
        )
        print(f"    Prejuizo total: R$ {total_brl:,.2f}")
    print()


# =============================================================
# Loop principal
# =============================================================
def print_menu() -> None:
    print("=" * 52)
    print(" SISTEMA DE PRODUCAO E PERDAS - CANA-DE-ACUCAR")
    print("=" * 52)
    print(" 1 - Cadastrar producao")
    print(" 2 - Listar producoes")
    print(" 3 - Apagar registro")
    print(" 4 - Exportar JSON")
    print(" 5 - Exportar relatorio TXT")
    print(" 6 - Resumo por tipo de colheita")
    print(" 0 - Sair")
    print("=" * 52)


def main() -> None:
    if not ORACLE_USER or not ORACLE_PASSWORD:
        print(
            "Configure as variaveis de ambiente antes de rodar:\n"
            "  export ORACLE_USER=rmXXXXXX\n"
            "  export ORACLE_PASSWORD=sua_senha\n"
            "  export ORACLE_DSN=oracle.fiap.com.br:1521/ORCL\n"
        )
        return

    try:
        create_table()
    except oracledb.DatabaseError as exc:
        print(f"Falha ao conectar no Oracle: {exc}")
        return

    actions: dict[str, Callable[[], None]] = {
        "1": action_register,
        "2": action_list,
        "3": action_delete,
        "4": action_export_json,
        "5": action_export_txt,
        "6": action_summary,
    }

    while True:
        print_menu()
        choice = input("Escolha: ").strip()
        if choice == "0":
            print("Encerrando.")
            break
        action = actions.get(choice)
        if action is None:
            print("  Opcao invalida.\n")
            continue
        try:
            action()
        except oracledb.DatabaseError as exc:
            print(f"  Erro de banco: {exc}\n")


if __name__ == "__main__":
    main()
